name: treechop-appo-baseline

global_settings:
  use_wandb: True

experiment_settings:
  save_every_sec: 120
  train_for_env_steps: 100000000

async_ppo:
  decorrelate_experience_max_seconds: 10
  experiment_summaries_interval: 5
  ppo_epochs: 1
  batch_size: 1024
  use_rnn: True
  max_grad_norm: 0.0


  worker_num_splits: 1
  num_workers:
    grid_search: [10]
  force_envs_single_thread:
    grid_search: [False]
  num_envs_per_worker:
    grid_search: [1]

environment:
  name: 'IGLUSilentBuilder-v0'
